services:
  axon-server:
    image: axoniq/axonserver:latest
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    ports:
      - "8024:8024"
      - "8124:8124"
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=admin123'
    ports:
      - "5432:5432"
    volumes:
      - axon-data:/var/lib/postgresql/data
    networks:
      - axon-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - "8088:80"
    networks:
      - axon-network

volumes:
    axon-data:
      driver: local
networks:
    axon-network:
      driver: bridge